### ISSUE TITLE
Moving mouse to upper right-hand corner on remote triggers close-window, titlebar-doubleclick and other double-click based issues.

### ISSUE THREAD

**Issue by rivthor** [truong2d/mm#33]
Subject says all...

Moving mouse to upper right-hand corner on remote triggers close-window, titlebar-doubleclick and other double-click based issues.

**Comment by Guru24** [comment]
Uncheck Wrap Mouse option in Other Options tab.
If this doesn't work, you can install the beta version

https://github.com/truong2d/mm/releases/tag/2.2.1

**Comment by rivthor** [comment]
Unchecking Wrap mouse turned out to be enough.

Sorry for being slow on closing the issue.
